Repository openziti/ziti-tunnel-android, pull requests merged in 2020-10, with the labels that each got.

#29 fix getting version code
  build.gradle
Labels: chore

#31 Build update gradle
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: chore, dependencies

#33 enable intercept of IP addresses
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/org/openziti/mobile/Tunnel.kt
  app/src/main/java/org/openziti/mobile/ZitiApp.kt
  app/src/main/java/org/openziti/mobile/ZitiMobileEdgeApp.kt
  app/src/main/java/org/openziti/mobile/ZitiVPNService.kt
  app/src/main/java/org/openziti/mobile/net/PacketRouterImpl.kt
  app/src/main/java/org/openziti/mobile/net/net.kt
  app/src/test/java/org/openziti/mobile/net/DNSManagerTest.kt
  build.gradle
  gradle.properties
Labels: enhancement, minor

#30 Fix UI Issues from last update.
  app/src/main/res/layout/dashboard.xml
  app/src/main/res/layout/identity.xml
  app/src/main/res/layout/identityitem.xml
Labels: enhancement, minor
